In [4]:
from pandasai import SmartDataframe
import pandas as pd
# memasukan csv kedalam dataframe
APU = SmartDataframe("~/project/APUChat/workspace/data/data_pencucian_uang.csv")

### cek dupkikasi data

In [9]:
response = APU.chat("IDENTIFIKASI DAN TAMPILKAN DATA DUPLIKAT DALAM DATASET")
print(response)

2023-09-18 04:56:04 [INFO] Question: IDENTIFIKASI DAN TAMPILKAN DATA DUPLIKAT DALAM DATASET
2023-09-18 04:56:04 [INFO] Running PandasAI with openai LLM...
2023-09-18 04:56:04 [INFO] Prompt ID: cd5eed68-b770-4187-b8e6-03b3365be5dc
2023-09-18 04:56:14 [INFO]
                    Code generated:
                    ```
                    # TODO import all the dependencies required
import pandas as pd

# Analyze the data
# 1. Prepare: Preprocessing and cleaning data if necessary
# 2. Process: Manipulating data for analysis (grouping, filtering, aggregating, etc.)
# 3. Analyze: Conducting the actual analysis (if the user asks to create a chart save it to an image in exports/charts/temp_chart.png and do not show the chart.)
# 4. Output: return a dictionary of:
# - type (possible values "text", "number", "dataframe", "plot")
# - value (can be a string, a dataframe or the path of the plot, NOT a dictionary)
# Example output: { "type": "text", "value": "The average loan amount is $15,000." }
def analyze_data(dfs: list[pd.DataFrame]) -> dict:
    # Code goes here (do not add comments)
    duplicates = []
    for df in dfs:
        duplicate_rows = df[df.duplicated()]
        if not duplicate_rows.empty:
            duplicates.append(duplicate_rows)

    if duplicates:
        result_df = pd.concat(duplicates)
        result = {"type": "dataframe", "value": result_df}
    else:
        result = {"type": "text", "value": "No duplicate rows found in the dataset."}

    return result


# Declare a result variable
result = analyze_data(dfs)
                    ```

2023-09-18 04:56:14 [INFO]
Code running:
```
def analyze_data(dfs: list[pd.DataFrame]) ->dict:
    duplicates = []
    for df in dfs:
        duplicate_rows = df[df.duplicated()]
        if not duplicate_rows.empty:
            duplicates.append(duplicate_rows)
    if duplicates:
        result_df = pd.concat(duplicates)
        result = {'type': 'dataframe', 'value': result_df}
    else:
        result = {'type': 'text', 'value': 'No duplicate rows found in the dataset.'}
    return result


result = analyze_data(dfs)
        ```
2023-09-18 04:56:14 [INFO] Answer: {'type': 'dataframe', 'value':              Nama Jenis Transaksi   Jumlah (Rp) Tanggal Transaksi  \
150    Pelanggan8     Tarik Tunai  4.631950e+07        2022-09-23
184    Pelanggan9     Tarik Tunai  2.983771e+06        2022-11-28
205   Pelanggan10        Transfer  2.645491e+07        2022-09-01
231    Pelanggan9         Deposit           NaN        2020-01-22
288    Pelanggan6         Deposit  7.366845e+06        2021-09-23
306    Pelanggan9     Tarik Tunai           NaN        2020-06-20
326    Pelanggan5         Deposit  4.755319e+07        2022-10-24
407    Pelanggan2        Transfer  3.135615e+07        2020-07-13
408   Pelanggan10        Transfer  4.839030e+07        2020-07-07
440    Pelanggan9         Deposit  2.233823e+07        2022-07-24
480    Pelanggan7     Tarik Tunai  1.789819e+07        2021-02-02
494    Pelanggan1         Deposit  4.048024e+07        2022-10-16
498    Pelanggan3         Deposit           NaN        2022-02-01
517    Pelanggan9        Transfer  3.051485e+07        2022-12-10
521    Pelanggan2         Deposit  2.651515e+07        2021-03-11
524           NaN     Tarik Tunai  2.372245e+07        2020-01-15
578    Pelanggan2        Transfer  4.920556e+07        2020-04-01
609    Pelanggan9        Transfer  3.406816e+07        2020-01-03
611    Pelanggan1             NaN  2.018244e+07        2022-05-21
621    Pelanggan8        Transfer  2.461203e+07        2022-10-30
623    Pelanggan2             NaN  1.394205e+07        2020-05-19
657    Pelanggan2        Transfer  2.452740e+07        2022-10-05
690    Pelanggan9         Deposit  2.479304e+07               NaN
714    Pelanggan6        Transfer  6.519173e+06        2022-03-06
716    Pelanggan4     Tarik Tunai           NaN        2020-06-09
733    Pelanggan6         Deposit  4.301146e+07        2020-03-16
754    Pelanggan3     Tarik Tunai  1.007435e+07        2022-06-03
778    Pelanggan5     Tarik Tunai  3.753215e+07        2020-11-24
787    Pelanggan6     Tarik Tunai  1.004210e+07        2022-11-22
796    Pelanggan3             NaN -4.789160e+07        2022-08-31
800           NaN     Tarik Tunai  3.891417e+07               NaN
834    Pelanggan9     Tarik Tunai  3.626598e+07        2021-04-14
868    Pelanggan7        Transfer  1.745274e+07        2022-11-07
874    Pelanggan5     Tarik Tunai  2.227364e+07        2021-06-21
879    Pelanggan5         Deposit  2.583076e+07        2020-01-14
915    Pelanggan1        Transfer  1.080911e+07        2020-04-02
934    Pelanggan9        Transfer  1.214084e+07        2022-09-03
937    Pelanggan5        Transfer  1.422953e+07        2022-04-23
947    Pelanggan7         Deposit  4.912116e+07        2022-03-27
955    Pelanggan7         Deposit  3.728453e+07        2020-01-18
966    Pelanggan2        Transfer  2.046364e+07        2022-02-01
974   Pelanggan10         Deposit  1.000000e+09        2020-01-06
990    Pelanggan9         Deposit -1.000000e+09        2021-11-21
1003   Pelanggan2     Tarik Tunai  7.059517e+06        2020-03-11
1011   Pelanggan4         Deposit  1.256694e+07               NaN
1015   Pelanggan5     Tarik Tunai  3.579774e+07        2021-03-05
1026   Pelanggan5         Deposit  4.412314e+07        2021-02-06
1031   Pelanggan6     Tarik Tunai  4.839616e+06        2022-01-28
1035   Pelanggan9     Tarik Tunai  2.177836e+06        2022-10-08
1042   Pelanggan5        Transfer  4.429868e+06        2021-08-15

              Lokasi  Jumlah (USD)
150          Jakarta   3308.535714
184          Bandung    213.126500
205         Surabaya   1889.636714
231         Surabaya           NaN
288          Jakarta    526.203214
306            Medan           NaN
326          Bandung   3396.656429
407          Jakarta   2239.724857
408          Bandung   3456.450071
440   TidakDiketahui   1595.588000
480            Medan   1278.442000
494      LokasiSalah   2891.445929
498       Yogyakarta           NaN
517         Surabaya   2179.632143
521          Bandung   1893.939000
524              NaN   1694.460857
578          Jakarta   3514.683143
609         Surabaya   2433.439786
611      LokasiSalah   1441.602714
621         Surabaya   1758.001929
623       Yogyakarta    995.860857
657          Bandung   1751.957500
690       Yogyakarta   1770.931786
714       Yogyakarta    465.655214
716       Yogyakarta           NaN
733          Jakarta   3072.246857
754       Yogyakarta    719.596571
778      LokasiSalah   2680.867857
787      LokasiSalah    717.293143
796          Bandung  -3420.828857
800         Surabaya   2779.583571
834            Medan   2590.427143
868         Surabaya   1246.624286
874          Bandung   1590.974143
879      LokasiSalah   1845.054214
915          Bandung    772.079000
934         Surabaya    867.203071
937       Yogyakarta   1016.394786
947       Yogyakarta   3508.654143
955         Surabaya   2663.180857
966              NaN   1461.688929
974          Bandung  71428.571429
990            Medan -71428.571429
1003     LokasiSalah    504.251214
1011  TidakDiketahui    897.638714
1015         Bandung   2556.981357
1026     LokasiSalah   3151.652857
1031      Yogyakarta    345.686857
1035         Jakarta    155.559714
1042         Jakarta    316.419143  }
2023-09-18 04:56:14 [INFO] Executed in: 9.943160057067871s
             Nama Jenis Transaksi   Jumlah (Rp) Tanggal Transaksi  \
150    Pelanggan8     Tarik Tunai  4.631950e+07        2022-09-23
184    Pelanggan9     Tarik Tunai  2.983771e+06        2022-11-28
205   Pelanggan10        Transfer  2.645491e+07        2022-09-01
231    Pelanggan9         Deposit           NaN        2020-01-22
288    Pelanggan6         Deposit  7.366845e+06        2021-09-23
306    Pelanggan9     Tarik Tunai           NaN        2020-06-20
326    Pelanggan5         Deposit  4.755319e+07        2022-10-24
407    Pelanggan2        Transfer  3.135615e+07        2020-07-13
408   Pelanggan10        Transfer  4.839030e+07        2020-07-07
440    Pelanggan9         Deposit  2.233823e+07        2022-07-24
480    Pelanggan7     Tarik Tunai  1.789819e+07        2021-02-02
494    Pelanggan1         Deposit  4.048024e+07        2022-10-16
498    Pelanggan3         Deposit           NaN        2022-02-01
517    Pelanggan9        Transfer  3.051485e+07        2022-12-10
521    Pelanggan2         Deposit  2.651515e+07        2021-03-11
524           NaN     Tarik Tunai  2.372245e+07        2020-01-15
578    Pelanggan2        Transfer  4.920556e+07        2020-04-01
609    Pelanggan9        Transfer  3.406816e+07        2020-01-03
611    Pelanggan1             NaN  2.018244e+07        2022-05-21
621    Pelanggan8        Transfer  2.461203e+07        2022-10-30
623    Pelanggan2             NaN  1.394205e+07        2020-05-19
657    Pelanggan2        Transfer  2.452740e+07        2022-10-05
690    Pelanggan9         Deposit  2.479304e+07               NaN
714    Pelanggan6        Transfer  6.519173e+06        2022-03-06
716    Pelanggan4     Tarik Tunai           NaN        2020-06-09
733    Pelanggan6         Deposit  4.301146e+07        2020-03-16
754    Pelanggan3     Tarik Tunai  1.007435e+07        2022-06-03
778    Pelanggan5     Tarik Tunai  3.753215e+07        2020-11-24
787    Pelanggan6     Tarik Tunai  1.004210e+07        2022-11-22
796    Pelanggan3             NaN -4.789160e+07        2022-08-31
800           NaN     Tarik Tunai  3.891417e+07               NaN
834    Pelanggan9     Tarik Tunai  3.626598e+07        2021-04-14
868    Pelanggan7        Transfer  1.745274e+07        2022-11-07
874    Pelanggan5     Tarik Tunai  2.227364e+07        2021-06-21
879    Pelanggan5         Deposit  2.583076e+07        2020-01-14
915    Pelanggan1        Transfer  1.080911e+07        2020-04-02
934    Pelanggan9        Transfer  1.214084e+07        2022-09-03
937    Pelanggan5        Transfer  1.422953e+07        2022-04-23
947    Pelanggan7         Deposit  4.912116e+07        2022-03-27
955    Pelanggan7         Deposit  3.728453e+07        2020-01-18
966    Pelanggan2        Transfer  2.046364e+07        2022-02-01
974   Pelanggan10         Deposit  1.000000e+09        2020-01-06
990    Pelanggan9         Deposit -1.000000e+09        2021-11-21
1003   Pelanggan2     Tarik Tunai  7.059517e+06        2020-03-11
1011   Pelanggan4         Deposit  1.256694e+07               NaN
1015   Pelanggan5     Tarik Tunai  3.579774e+07        2021-03-05
1026   Pelanggan5         Deposit  4.412314e+07        2021-02-06
1031   Pelanggan6     Tarik Tunai  4.839616e+06        2022-01-28
1035   Pelanggan9     Tarik Tunai  2.177836e+06        2022-10-08
1042   Pelanggan5        Transfer  4.429868e+06        2021-08-15

              Lokasi  Jumlah (USD)
150          Jakarta   3308.535714
184          Bandung    213.126500
205         Surabaya   1889.636714
231         Surabaya           NaN
288          Jakarta    526.203214
306            Medan           NaN
326          Bandung   3396.656429
407          Jakarta   2239.724857
408          Bandung   3456.450071
440   TidakDiketahui   1595.588000
480            Medan   1278.442000
494      LokasiSalah   2891.445929
498       Yogyakarta           NaN
517         Surabaya   2179.632143
521          Bandung   1893.939000
524              NaN   1694.460857
578          Jakarta   3514.683143
609         Surabaya   2433.439786
611      LokasiSalah   1441.602714
621         Surabaya   1758.001929
623       Yogyakarta    995.860857
657          Bandung   1751.957500
690       Yogyakarta   1770.931786
714       Yogyakarta    465.655214
716       Yogyakarta           NaN
733          Jakarta   3072.246857
754       Yogyakarta    719.596571
778      LokasiSalah   2680.867857
787      LokasiSalah    717.293143
796          Bandung  -3420.828857
800         Surabaya   2779.583571
834            Medan   2590.427143
868         Surabaya   1246.624286
874          Bandung   1590.974143
879      LokasiSalah   1845.054214
915          Bandung    772.079000
934         Surabaya    867.203071
937       Yogyakarta   1016.394786
947       Yogyakarta   3508.654143
955         Surabaya   2663.180857
966              NaN   1461.688929
974          Bandung  71428.571429
990            Medan -71428.571429
1003     LokasiSalah    504.251214
1011  TidakDiketahui    897.638714
1015         Bandung   2556.981357
1026     LokasiSalah   3151.652857
1031      Yogyakarta    345.686857
1035         Jakarta    155.559714
1042         Jakarta    316.419143

In [5]:
response = APU.chat("ada berapa baris jumlah data yang hilang?")
print(response)

2023-09-20 08:34:39 [INFO] Question: ada berapa baris jumlah data yang hilang?
2023-09-20 08:34:39 [INFO] Running PandasAI with openai LLM...
2023-09-20 08:34:39 [INFO] Prompt ID: ad892294-d7b3-478c-b5c6-28fcdafb84fd
2023-09-20 08:34:50 [INFO]
                    Code generated:
                    ```
                    # TODO import all the dependencies required
import pandas as pd

# Analyze the data
# 1. Prepare: Preprocessing and cleaning data if necessary
# 2. Process: Manipulating data for analysis (grouping, filtering, aggregating, etc.)
# 3. Analyze: Conducting the actual analysis (if the user asks to create a chart save it to an image in exports/charts/temp_chart.png and do not show the chart.)
# 4. Output: return a dictionary of:
# - type (possible values "text", "number", "dataframe", "plot")
# - value (can be a string, a dataframe or the path of the plot, NOT a dictionary)
# Example output: { "type": "text", "value": "The average loan amount is $15,000." }
def analyze_data(dfs: list[pd.DataFrame]) -> dict:
    # Code goes here (do not add comments)
    missing_data_count = dfs[0].isnull().sum().sum()
    return {"type": "number", "value": missing_data_count}

# Declare a result variable
result = analyze_data(dfs)
                    ```

2023-09-20 08:34:50 [INFO]
Code running:
```
def analyze_data(dfs: list[pd.DataFrame]) ->dict:
    missing_data_count = dfs[0].isnull().sum().sum()
    return {'type': 'number', 'value': missing_data_count}


result = analyze_data(dfs)
        ```
2023-09-20 08:34:50 [INFO] Answer: {'type': 'number', 'value': 318}
2023-09-20 08:34:50 [INFO] Executed in: 10.820835590362549s
318

In [14]:
response = APU.chat("identifikasi kolom dengan nilai hilang?")

2023-09-18 05:29:29 [INFO] Question: identifikasi kolom dengan nilai hilang?
2023-09-18 05:29:29 [INFO] Running PandasAI with openai LLM...
2023-09-18 05:29:29 [INFO] Prompt ID: a66ff491-a594-4e05-9a4e-ad19d752b863
2023-09-18 05:29:38 [INFO]
                    Code generated:
                    ```
                    # TODO import all the dependencies required
import pandas as pd

# Analyze the data
# 1. Prepare: Preprocessing and cleaning data if necessary
# 2. Process: Manipulating data for analysis (grouping, filtering, aggregating, etc.)
# 3. Analyze: Conducting the actual analysis (if the user asks to create a chart save it to an image in exports/charts/temp_chart.png and do not show the chart.)
# 4. Output: return a dictionary of:
# - type (possible values "text", "number", "dataframe", "plot")
# - value (can be a string, a dataframe or the path of the plot, NOT a dictionary)
# Example output: { "type": "text", "value": "The average loan amount is $15,000." }
def analyze_data(dfs: list[pd.DataFrame]) -> dict:
    # Code goes here (do not add comments)
    missing_values = []
    for df in dfs:
        missing_values.extend(df.columns[df.isnull().any()].tolist())
    missing_columns = list(set(missing_values))
    return {"type": "text", "value": f"The columns with missing values are: {', '.join(missing_columns)}."}

# Declare a result variable
result = analyze_data(dfs)
                    ```

2023-09-18 05:29:38 [INFO]
Code running:
```
def analyze_data(dfs: list[pd.DataFrame]) ->dict:
    missing_values = []
    for df in dfs:
        missing_values.extend(df.columns[df.isnull().any()].tolist())
    missing_columns = list(set(missing_values))
    return {'type': 'text', 'value': f"The columns with missing values are: {', '.join(missing_columns)}."}


result = analyze_data(dfs)
        ```
2023-09-18 05:29:38 [INFO] Answer: {'type': 'text', 'value': 'The columns with missing values are: Jumlah (Rp), Jumlah (USD), Jenis Transaksi, Tanggal Transaksi, Nama, Lokasi.'}
2023-09-18 05:29:38 [INFO] Executed in: 8.431430101394653s

In [2]:
response = APU.chat("sebutkan presentase nilai yang hilang dalam dataset?")
print(response)

2023-09-18 11:27:01 [INFO] Question: sebutkan presentase nilai yang hilang dalam dataset?
2023-09-18 11:27:01 [INFO] Running PandasAI with openai LLM...
2023-09-18 11:27:01 [INFO] Prompt ID: 7617ff4d-c6df-4657-85de-d05364379c88
2023-09-18 11:27:13 [INFO]
                    Code generated:
                    ```
                    # TODO import all the dependencies required
import pandas as pd

# Analyze the data
# 1. Prepare: Preprocessing and cleaning data if necessary
# 2. Process: Manipulating data for analysis (grouping, filtering, aggregating, etc.)
# 3. Analyze: Conducting the actual analysis (if the user asks to create a chart save it to an image in exports/charts/temp_chart.png and do not show the chart.)
# 4. Output: return a dictionary of:
# - type (possible values "text", "number", "dataframe", "plot")
# - value (can be a string, a dataframe or the path of the plot, NOT a dictionary)
# Example output: { "type": "text", "value": "The average loan amount is $15,000." }
def analyze_data(dfs: list[pd.DataFrame]) -> dict:
    # Calculate the percentage of missing values in each dataframe
    missing_percentage = []
    for df in dfs:
        percentage = df.isnull().sum().sum() / (df.shape[0] * df.shape[1]) * 100
        missing_percentage.append(percentage)

    # Return the result as a text
    result_text = "The percentage of missing values in the dataset is: "
    for i, percentage in enumerate(missing_percentage):
        result_text += f"\n- DataFrame {i+1}: {percentage:.2f}%"

    return {"type": "text", "value": result_text}

# Declare a result variable
result = analyze_data(dfs)
                    ```

2023-09-18 11:27:13 [INFO]
Code running:
```
def analyze_data(dfs: list[pd.DataFrame]) ->dict:
    missing_percentage = []
    for df in dfs:
        percentage = df.isnull().sum().sum() / (df.shape[0] * df.shape[1]) * 100
        missing_percentage.append(percentage)
    result_text = 'The percentage of missing values in the dataset is: '
    for i, percentage in enumerate(missing_percentage):
        result_text += f'\n- DataFrame {i + 1}: {percentage:.2f}%'
    return {'type': 'text', 'value': result_text}


result = analyze_data(dfs)
        ```
2023-09-18 11:27:13 [INFO] Answer: {'type': 'text', 'value': 'The percentage of missing values in the dataset is: \n- DataFrame 1: 5.05%'}
2023-09-18 11:27:13 [INFO] Executed in: 12.22946572303772s
The percentage of missing values in the dataset is:
- DataFrame 1: 5.05%

In [3]:
print(SmartDataframe)

<class 'pandasai.smart_dataframe.SmartDataframe'>